export { default as WrapperContentBody } from './WrapperContentBody'
export { default as TableEmployee } from './TableEmployee'
export { default as TableCategory } from './TableCategory'
export { default as TableDepartment } from './TableDepartment'
export { default as TableEquipment } from './TableEquipment'